# Generated by Django 4.1 on 2022-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadBasica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "concessionaria",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=50)),
                ("desnivel", models.IntegerField()),
                ("vazao", models.IntegerField()),
                ("modelo", models.CharField(max_length=10)),
                ("potencia", models.IntegerField()),
                ("mchs", models.IntegerField()),
                ("data", models.DateField()),
            ],
        ),
    ]
