# Generated by Django 4.1 on 2022-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadbasica",
            name="modelo",
            field=models.CharField(
                choices=[("On", "On Grid"), ("Off", "Off Grid")],
                default="On",
                max_length=10,
            ),
        ),
    ]
