# Generated by Django 4.1 on 2022-08-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0002_alter_leadbasica_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadbasica",
            name="mchs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leadbasica",
            name="potencia",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
