# Generated by Django 4.1 on 2022-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0004_alter_leadbasica_mchs_alter_leadbasica_potencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadbasica",
            name="potencia",
        ),
        migrations.AlterField(
            model_name="leadbasica",
            name="mchs",
            field=models.IntegerField(default=0),
        ),
    ]
