# Generated by Django 4.1 on 2022-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0005_remove_leadbasica_potencia_alter_leadbasica_mchs"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadbasica",
            name="potencia",
            field=models.IntegerField(default=0),
        ),
    ]
