# Generated by Django 4.1 on 2022-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0007_leadavancada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadavancada",
            name="tipo_cabo",
            field=models.CharField(
                choices=[("A", "Alumínio"), ("C", "Cobre")], default="A", max_length=10
            ),
        ),
    ]
