# Generated by Django 4.1 on 2022-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculadoras",
            "0009_leadavancada_bitola_real_leadavancada_desnivel_real_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadavancada",
            name="porcentagem_perda",
            field=models.CharField(max_length=10),
        ),
    ]
